markdown: redcarpet
pygments: true

title_tag_text: PicoAVR, A minimalistic solution for AVR development
h1_tag_text: PicoAVR

exclude: ["Procfile", "Gruntfile.js", "README.md", "package.json", "node_modules"]

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
